      IF(MOD(ITER,NUNUTAR).EQ.0.OR.ITER.EQ.1) THEN 
!-------
      IF(.NOT.LTRANSIENT) THEN
      WRITE(6,"(1X,I5,1X,1P,9E9.2,1P,9E10.2)")ITIME, &
          (RESOR(I),I=1,7),RESOR(IVART),RESOR(ICON), &
          U(IJKMON),V(IJKMON),W(IJKMON),P(IJKMON), &
          TE(IJKMON),ED(IJKMON),T(IJKMON),VART(IJKMON), &
          CON(IJKMON)
      END IF
      IF(LTRANSIENT.and.SIMPLE) THEN
      WRITE(6,"(1X,I5,1X,1P,9E9.2,1P,9E10.2)")ITER, &
          (RESOR(I),I=1,7),RESOR(IVART),RESOR(ICON), &
          U(IJKMON),V(IJKMON),W(IJKMON),P(IJKMON), &
          TE(IJKMON),ED(IJKMON),T(IJKMON),VART(IJKMON), &
          CON(IJKMON)
      END IF
!-------
      END IF
